num_1 = int(input("Enter your number :"))
num_2 = int(input("Enter your number :"))
print(num_1, "+", num_2, "=" ,num_1 + num_2)
print(num_1, "-", num_2, "=" ,num_1 - num_2)
print(num_1, "*", num_2, "=" ,num_1 * num_2)
print(num_1, "/", num_2, "=" ,num_1 / num_2)